__type: res_desc_pct
downsampled: false
header:
  faceSize: 10000
  format: 52
  mipLevel:
  - offset: 0
    size: 10000
  nFaces: 1
  nMipMap: 1
  sign: 1346978644
  size: 10000
  sx: 100
  sy: 100
  sz: 1
imageOffset: 72
isCopyDst: false
isImposter: false
isLightmap: false
linkTd: res://td/lpd_luna_wolves.td.resource
mipMaps: []
pct: lpd_luna_wolves.pct
predownsampleMipsCount: 0
source: source\textures\ui\decals_icons\lpd_luna_wolves.tga
texName: lpd_luna_wolves
texType: ''
tileLayout: 0
tiles: []
useHeaderFromResource: source\textures\ui\decals_icons\lpd_luna_wolves.tga
