__type: res_desc_pct
downsampled: true
header:
  faceSize: 1398096
  format: 51
  mipLevel:
  - offset: 0
    size: 1048576
  - offset: 1048576
    size: 262144
  - offset: 1310720
    size: 65536
  - offset: 1376256
    size: 16384
  - offset: 1392640
    size: 4096
  - offset: 1396736
    size: 1024
  - offset: 1397760
    size: 256
  - offset: 1398016
    size: 64
  - offset: 1398080
    size: 16
  nFaces: 1
  nMipMap: 9
  sign: 1346978644
  size: 1398096
  sx: 1024
  sy: 1024
  sz: 1
imageOffset: 0
isCopyDst: false
isImposter: false
isLightmap: false
linkTd: res://td/d_shldr_user_texture_01_r_cc.td.resource
mipMaps:
- d_shldr_user_texture_01_r_cc_1.pct_mip
- d_shldr_user_texture_01_r_cc_2.pct_mip
- d_shldr_user_texture_01_r_cc_3.pct_mip
- d_shldr_user_texture_01_r_cc_4.pct_mip
- d_shldr_user_texture_01_r_cc_5.pct_mip
- d_shldr_user_texture_01_r_cc_6.pct_mip
- d_shldr_user_texture_01_r_cc_7.pct_mip
- d_shldr_user_texture_01_r_cc_8.pct_mip
- d_shldr_user_texture_01_r_cc_9.pct_mip
pct: ''
predownsampleMipsCount: 10
source: ''
texName: d_shldr_user_texture_01_r_cc
texType: ''
tileLayout: 0
tiles: []
useHeaderFromResource: true
